<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Roleinfo</name>
   <tag></tag>
   <elementGuidId>ca6cb102-a0b6-4cb0-9dfd-5abb95920ef1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[(text() = 'demo' or . = 'demo')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a3b2ab5b-d8d3-49fa-854e-1eeeacb9ae1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>demo</value>
      <webElementGuid>24c63fed-2528-4a73-8f0d-1efd82a30c61</webElementGuid>
   </webElementProperties>
</WebElementEntity>
