<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>GenericTestSuite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>c0b3d89d-ec76-43b1-b9a6-1bce73d8cdc7</testSuiteGuid>
   <testCaseLink>
      <guid>69c07e6c-ab8b-4590-9680-a4b370aab2f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2019.3/AltairAccesslogo_JobsTab</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>015be0ef-4498-4dcd-9c0f-8644f8b7aebe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee1669e4-484d-446c-a6cd-6805d5cfa8fd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>36f51e78-373a-418e-b670-30a61cf78421</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2019.3/Bookmark_JobSubmissionForm</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>cd8a1afb-94df-4f49-92b6-271051e94843</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForBookMarks</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>342bf84f-d731-46b2-bc09-0598f54f2c06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cd8a1afb-94df-4f49-92b6-271051e94843</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>6e957165-146e-463b-a224-778888e896fe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cd8a1afb-94df-4f49-92b6-271051e94843</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>bookMarkName</value>
         <variableId>98ebd070-a82f-4332-81d4-243dafc56d70</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cd8a1afb-94df-4f49-92b6-271051e94843</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>option</value>
         <variableId>c0fd68ee-be16-489f-b4f8-96a8f6773260</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cd8a1afb-94df-4f49-92b6-271051e94843</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>location</value>
         <variableId>d176fffb-2637-4b0d-99e5-8010ae6b4d00</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9fa49202-fee8-4fed-9fdb-0c148898ec2f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2019.3/ProcessWith_Optistruct</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ecebbc7d-c682-48a7-ae90-b89b965c63d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee159a2f-337e-4f8f-84d6-4c5206a6e4f2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13bb1d38-b7f1-4761-8678-46a35eed5c08</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2d3c70e3-888f-40f4-bb8a-f930c94139d2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Generic/LoginTestCase</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>55e736d2-9b0a-47c4-8cc4-6682ccdcc7c1</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForLogin</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>55e736d2-9b0a-47c4-8cc4-6682ccdcc7c1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>8bcef31e-0732-4fba-bd3b-e4bce98ba19c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>55e736d2-9b0a-47c4-8cc4-6682ccdcc7c1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>a63c7d7f-f42d-46cf-aa3c-404ff99616fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>55e736d2-9b0a-47c4-8cc4-6682ccdcc7c1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>877994f5-2889-4f28-9a03-5b6c724d598a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>55e736d2-9b0a-47c4-8cc4-6682ccdcc7c1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>7779819d-719f-416d-9ac2-1ce4255afe2c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ac78f1d6-3ef0-4c58-a7ae-8651bc414cee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WindowTitle/BrowserVersion</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4601ff3c-2fec-4c45-a234-b1a99245f66f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>be419209-23d1-4b1d-947b-6d57438eda93</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WindowTitle/GetWindowTitle</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7e16d2e-0b13-4e73-957e-8575c0bc254e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66aa9127-13ad-43ab-a072-53eea7e467e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e26fe06-f737-4bad-8a94-3ce18a62cbb4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32ed20d1-8dca-4e69-8531-241f053a6b06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3080d45e-d09d-41dd-9260-5c6b4f00d2ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>826205c1-167c-46ec-9ce3-1cdfc16899ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98fa2418-ff60-4297-8a4f-c8ccc94897e5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d2fdb77a-527c-4749-9cd1-216ea26f248d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WindowTitle/JobApplicationFilterVerification</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b292f73-6e4e-44a1-afc8-5515f4bae6f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89e76b7e-4494-4c6e-ba5e-4dc4c0ebf02e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af74ead0-ad1a-48e1-9136-865ab3d1a631</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f81dc48-02c2-4203-b874-992fce0dd013</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2f7d5a11-cfa1-4666-ae34-b64e8039d283</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WindowTitle/JobColumnVerification</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b717dc8a-b8de-44cd-bde5-6c2f3419754b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92cfa93b-f45c-4806-b38e-d3069f59b16b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd27047a-f290-4db7-a132-87197302a1fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c562e8d8-b57e-447b-a968-93b5d778e6ca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8837c03c-6bb4-4f29-b5bd-45ea002c0ebb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/2019.3/RunningFolder_UploadFile</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>04eb5cd4-5982-4990-9331-4a7cd5c4086a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b45b6c8c-8a07-4e38-8fd1-685dffd2e8f8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2495b9a2-4866-425f-b5d0-edc81a39402a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
