<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>JobsRFB-FileOperations-DryRunsExtent</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>e7def78f-5f8e-4830-887a-1d6960f0e70f</testSuiteGuid>
   <testCaseLink>
      <guid>67e150e7-d6c1-4380-8e4f-696558567c9d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-MultiFileOperations</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2e87df9f-6ea8-49e2-a8fa-78df7a77aadd</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-10</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForFileOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>2e87df9f-6ea8-49e2-a8fa-78df7a77aadd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>12db675c-16c4-4b33-923e-3e90b3058e44</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2e87df9f-6ea8-49e2-a8fa-78df7a77aadd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>b92913c3-e2c8-41b6-ac34-0471f3e92e31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2e87df9f-6ea8-49e2-a8fa-78df7a77aadd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Operation</value>
         <variableId>efeae6f4-3f3e-4588-8af0-34464c4bba6a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ffa7487-f9f3-4b2a-9f86-0246012527f7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b9fcc341-1409-4a24-a5a3-4b1828a90f7f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-FolderOperations</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0d6aac11-94cd-4129-b829-ef8f8f1f273d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForFolderOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>0d6aac11-94cd-4129-b829-ef8f8f1f273d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FolderName</value>
         <variableId>8105a991-43b5-43b0-8b1f-ee3f69e92345</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb4f6178-1b28-43aa-933b-1eb3ee68a864</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0d6aac11-94cd-4129-b829-ef8f8f1f273d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>1ce8f2e1-64d6-42e2-8daa-c642b7eaca9e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0d6aac11-94cd-4129-b829-ef8f8f1f273d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Operation</value>
         <variableId>0025ea3f-58a9-4de0-8d6b-0a01c78a12ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45eaf3c1-c83b-40c5-9ffe-02caf94b28a0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7e845faf-e890-4be9-baa3-f07c4dba1c71</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-AddJobFiles</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea55ab9f-206e-4fcf-9ae0-7848cbada80d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea661e7b-c276-42ef-a6c9-1c1ef53f2265</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73d599e9-d250-4bbc-8dc9-b8509e150c37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acd0c7cf-20ad-4071-a100-4a42f1e373db</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d69712fe-4c49-49b0-9d26-da5e0cdabea6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-FileViewerOps</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8be63bac-385b-407f-a237-9775212153c1</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForFileViewer</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23b5d174-8326-4309-a461-a3a8b349eae4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8be63bac-385b-407f-a237-9775212153c1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FileName</value>
         <variableId>9b065ca7-abb9-4e53-9e42-92fff2b43874</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8be63bac-385b-407f-a237-9775212153c1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>c398326f-2040-448d-b714-a3071a0cdb4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9bfd2275-d015-4425-85f4-42fe0a1e3d40</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8be63bac-385b-407f-a237-9775212153c1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>33e3f1bb-053e-464d-a46d-f795250201eb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b1c73871-9c46-4945-8946-10b98fbaad55</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-AddJobScriptOption</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64ee1de1-1828-4d77-becb-8baf24e6e6ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1dd6665d-d333-4782-aad2-e1ca7324e28b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81884a8a-59c5-4af6-bb63-42db2be49040</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d6db54c-3469-4145-9d4e-a9761c738769</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4597ada2-27be-4cf2-95ed-09cd1aa0ac96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4501daa1-5d8a-4a59-b977-3109d0847ebe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0a7aec1-e16f-470f-b0f2-8b6360f0599c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7cbcb672-983b-43b0-bd2b-c56870a757ed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>58ab924e-bd61-4de6-a970-3841e7ccba0d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-InvalidPath</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b852c29-2a95-473d-955d-ed3bbe631419</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94f63a41-04d8-46ce-a37b-ae2b3074fd43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfa17c7d-5dd5-4bf7-9c99-aed96fe86e0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ee91afc-9df8-4d4f-86a7-9c1144499de1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1d9cf045-389a-43ab-b6e7-401489c4f6d6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-switchApplication</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5fc2ade-2b0d-4f8c-9c81-250fff92cae5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6413bb5-8219-4755-a651-79cc0c9b129f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d136fd6a-f3fa-44c6-bfda-d4211751b61f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11230f5d-2647-4379-8eb7-5ddb6672c072</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e50dac30-7a76-48be-b01d-426bbf80bc96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>622ae497-c74e-472f-972d-2996e7120e60</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8069fdf6-a7e8-4a98-a069-6b490517dd12</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-VerifyLabel</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8b4b244-4333-4de5-9a0f-fd535ae77ba6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>599df223-1449-4c1b-9b52-6bcc122ef427</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac8b30c6-a5ee-4ad6-bea9-46a99d790ec3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bdcb4e31-ed5c-4563-a88c-3612571a44ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-FileOperations</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>79d710a3-ebd9-4679-9fdf-473c2af2c8f0</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value>9</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForFileOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>295020a0-90c1-43b3-b6b1-8be5bdf98484</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>79d710a3-ebd9-4679-9fdf-473c2af2c8f0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FileName</value>
         <variableId>d7386246-6246-4cc7-b688-3ceed1d43158</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>79d710a3-ebd9-4679-9fdf-473c2af2c8f0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>eaebe514-d89a-4eb9-9d9f-8d87bb9fbb58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>79d710a3-ebd9-4679-9fdf-473c2af2c8f0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>IconOperation</value>
         <variableId>62f61e34-294a-4077-afd6-a99d73244bdb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2452730a-fb63-4365-92a2-2ba74197dafc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>79d710a3-ebd9-4679-9fdf-473c2af2c8f0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Operation</value>
         <variableId>f7e20caf-abd7-45d3-b8eb-a35fe4e133fb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e8d398ba-7706-492c-bb9c-2b1bd4be8ffe</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmissionForLastSubmitted</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>71100be0-cee7-40fc-b219-491472ab76f5</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>13-14</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForJobMonitoringGenericOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2165b182-636d-4b7f-ade2-161fca571166</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc34a078-3b76-4c35-9aca-e5bdde596154</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>71100be0-cee7-40fc-b219-491472ab76f5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>8593a4b9-9f88-428e-ba17-b836e798acf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e5d3486-4f6d-4c60-b9f7-f852e8083cf1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6ecc3a3-627b-4125-86fb-cb2431021897</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d935056-a60a-4f76-a4d1-527bbd6f770d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3c1226f-d56d-4cdf-ab0d-cd98ce0d3fa2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>71100be0-cee7-40fc-b219-491472ab76f5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>0d0853fe-9935-4957-956d-2f65728efe35</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b5fe689d-fa78-472f-822a-d6f9a5c4d28a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission_Reset</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d092280c-55eb-4a78-af85-fffafe1f88e0</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>8-10</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForJobMonitoringGenericOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d092280c-55eb-4a78-af85-fffafe1f88e0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>9d060f0b-9277-43e9-8c05-317c9ed897bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d040abb9-7351-4685-b440-05d8801dd4bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d092280c-55eb-4a78-af85-fffafe1f88e0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>debc6772-d8e4-4397-a148-25d8cf3db661</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>365bc496-2a6c-4edb-852f-22b91da13358</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission_LeaveForm</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>19255bed-729c-4d0d-90e4-0f1ff3b3ae65</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>5-7</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForJobMonitoringGenericOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>19255bed-729c-4d0d-90e4-0f1ff3b3ae65</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>eafa6e12-0135-42fc-b1ff-a3f118a8a163</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7719920b-c14d-43fe-a629-bcb6b8101040</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>19255bed-729c-4d0d-90e4-0f1ff3b3ae65</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>005889aa-cf57-4be6-a956-bb131f6725ca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3eb5a10a-9972-4dc8-bdb8-cc05a8b66d21</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/MultipleJobSubmissions</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53d74077-eef0-44bf-a79a-ebb3b3690ba9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d34d24f-5e83-48ff-881f-4d9620e2e4c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc913d2d-7bc7-4ca8-a5ec-62e6669bdb3e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b343cf64-59cb-478e-b7d7-197d3d3f3f72</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-NavigatingPreviousFolder</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91eeea77-0135-448f-8089-ed42cb63d23d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49b64022-8afd-42b1-95c6-b05be9bece94</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4159cb7-03c4-41d9-b199-73357b3822db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bd968dd8-ccc8-4734-bfaa-6318ad834c85</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
