<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>TxtBx_saveProfile</name>
   <tag></tag>
   <elementGuidId>6e3d72fa-b0e6-4f2b-bada-4bc2bffd174e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'save_profile_dlg_name_fld']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9003257f-094c-4f88-957f-923dbe4feb57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>save_profile_dlg_name_fld</value>
      <webElementGuid>0008ef1c-fe86-4bb6-ae48-25b851f74189</webElementGuid>
   </webElementProperties>
</WebElementEntity>
