<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>JRFB-FileOps_3</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>4d0b72f9-c9cd-45fe-b55e-e387b89ee021</testSuiteGuid>
   <testCaseLink>
      <guid>1ec98179-05be-43e1-b25f-1f9d15ad2a49</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-FileOperations</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>b7bab5ce-3702-4ec9-8835-915c9681340f</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1,3,5,7,9</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForFileOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>295020a0-90c1-43b3-b6b1-8be5bdf98484</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b7bab5ce-3702-4ec9-8835-915c9681340f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FileName</value>
         <variableId>d7386246-6246-4cc7-b688-3ceed1d43158</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b7bab5ce-3702-4ec9-8835-915c9681340f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>eaebe514-d89a-4eb9-9d9f-8d87bb9fbb58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>b7bab5ce-3702-4ec9-8835-915c9681340f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Operation</value>
         <variableId>62f61e34-294a-4077-afd6-a99d73244bdb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2452730a-fb63-4365-92a2-2ba74197dafc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06088c48-c331-4396-97c3-01d04194b342</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b9fcc341-1409-4a24-a5a3-4b1828a90f7f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-FolderOperations</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0d6aac11-94cd-4129-b829-ef8f8f1f273d</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1,3,5,7,9</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForFolderOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>0d6aac11-94cd-4129-b829-ef8f8f1f273d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FolderName</value>
         <variableId>8105a991-43b5-43b0-8b1f-ee3f69e92345</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb4f6178-1b28-43aa-933b-1eb3ee68a864</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0d6aac11-94cd-4129-b829-ef8f8f1f273d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>1ce8f2e1-64d6-42e2-8daa-c642b7eaca9e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0d6aac11-94cd-4129-b829-ef8f8f1f273d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Operation</value>
         <variableId>0025ea3f-58a9-4de0-8d6b-0a01c78a12ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45eaf3c1-c83b-40c5-9ffe-02caf94b28a0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d69712fe-4c49-49b0-9d26-da5e0cdabea6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-FileViewerOps</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8be63bac-385b-407f-a237-9775212153c1</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-6</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForFileViewer</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23b5d174-8326-4309-a461-a3a8b349eae4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8be63bac-385b-407f-a237-9775212153c1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FileName</value>
         <variableId>9b065ca7-abb9-4e53-9e42-92fff2b43874</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8be63bac-385b-407f-a237-9775212153c1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>c398326f-2040-448d-b714-a3071a0cdb4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9bfd2275-d015-4425-85f4-42fe0a1e3d40</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8be63bac-385b-407f-a237-9775212153c1</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>33e3f1bb-053e-464d-a46d-f795250201eb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>eb072d61-820b-4d10-982b-a18b07ad8056</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-InvalidPath</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b852c29-2a95-473d-955d-ed3bbe631419</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94f63a41-04d8-46ce-a37b-ae2b3074fd43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfa17c7d-5dd5-4bf7-9c99-aed96fe86e0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ee91afc-9df8-4d4f-86a7-9c1144499de1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4ab1a29d-00d2-4f97-9849-41ae41732e9c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-VerifyLabel</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8b4b244-4333-4de5-9a0f-fd535ae77ba6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>599df223-1449-4c1b-9b52-6bcc122ef427</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac8b30c6-a5ee-4ad6-bea9-46a99d790ec3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>361e8175-32d8-41b2-96e5-0b2b760bbdcb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-switchApplication</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5fc2ade-2b0d-4f8c-9c81-250fff92cae5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6413bb5-8219-4755-a651-79cc0c9b129f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d136fd6a-f3fa-44c6-bfda-d4211751b61f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11230f5d-2647-4379-8eb7-5ddb6672c072</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e50dac30-7a76-48be-b01d-426bbf80bc96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>622ae497-c74e-472f-972d-2996e7120e60</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
