<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>JRFB-FileOps_2</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>d0762d85-f6a3-4a45-adf8-dfdb32b13369</testSuiteGuid>
   <testCaseLink>
      <guid>bdcb4e31-ed5c-4563-a88c-3612571a44ac</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-FileOperations</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>79d710a3-ebd9-4679-9fdf-473c2af2c8f0</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1,3,5,7,9</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForFileOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>295020a0-90c1-43b3-b6b1-8be5bdf98484</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>79d710a3-ebd9-4679-9fdf-473c2af2c8f0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FileName</value>
         <variableId>d7386246-6246-4cc7-b688-3ceed1d43158</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>79d710a3-ebd9-4679-9fdf-473c2af2c8f0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>eaebe514-d89a-4eb9-9d9f-8d87bb9fbb58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>79d710a3-ebd9-4679-9fdf-473c2af2c8f0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>IconOperation</value>
         <variableId>62f61e34-294a-4077-afd6-a99d73244bdb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2452730a-fb63-4365-92a2-2ba74197dafc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06088c48-c331-4396-97c3-01d04194b342</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>dae2ef31-f4a6-45b8-9325-2b61f3236e2d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-MultiFileOperations</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a2eda6e4-c2dc-417c-a95f-2dcd645f0c43</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1,3,5,7,9</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForFileOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>a2eda6e4-c2dc-417c-a95f-2dcd645f0c43</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>12db675c-16c4-4b33-923e-3e90b3058e44</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a2eda6e4-c2dc-417c-a95f-2dcd645f0c43</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>b92913c3-e2c8-41b6-ac34-0471f3e92e31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a2eda6e4-c2dc-417c-a95f-2dcd645f0c43</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>IconOperation</value>
         <variableId>efeae6f4-3f3e-4588-8af0-34464c4bba6a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ffa7487-f9f3-4b2a-9f86-0246012527f7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b9fcc341-1409-4a24-a5a3-4b1828a90f7f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-FolderOperations</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0d6aac11-94cd-4129-b829-ef8f8f1f273d</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1,3,5,7,9,11</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForFolderOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>0d6aac11-94cd-4129-b829-ef8f8f1f273d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FolderName</value>
         <variableId>8105a991-43b5-43b0-8b1f-ee3f69e92345</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eb4f6178-1b28-43aa-933b-1eb3ee68a864</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0d6aac11-94cd-4129-b829-ef8f8f1f273d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>1ce8f2e1-64d6-42e2-8daa-c642b7eaca9e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0d6aac11-94cd-4129-b829-ef8f8f1f273d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Operation</value>
         <variableId>0025ea3f-58a9-4de0-8d6b-0a01c78a12ac</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45eaf3c1-c83b-40c5-9ffe-02caf94b28a0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b5fe689d-fa78-472f-822a-d6f9a5c4d28a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission_Reset</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d092280c-55eb-4a78-af85-fffafe1f88e0</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>8-10</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForJobMonitoringGenericOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>d092280c-55eb-4a78-af85-fffafe1f88e0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>9d060f0b-9277-43e9-8c05-317c9ed897bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d040abb9-7351-4685-b440-05d8801dd4bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d092280c-55eb-4a78-af85-fffafe1f88e0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>debc6772-d8e4-4397-a148-25d8cf3db661</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
