<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>JRFB-FileOps_1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>5b1d2265-8f25-4abe-8c50-f63aa2577728</testSuiteGuid>
   <testCaseLink>
      <guid>67e150e7-d6c1-4380-8e4f-696558567c9d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-MultiFileOperations</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2e87df9f-6ea8-49e2-a8fa-78df7a77aadd</id>
         <iterationEntity>
            <iterationType>SPECIFIC</iterationType>
            <value>1,3,5,7,9</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForFileOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>2e87df9f-6ea8-49e2-a8fa-78df7a77aadd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>12db675c-16c4-4b33-923e-3e90b3058e44</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2e87df9f-6ea8-49e2-a8fa-78df7a77aadd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>b92913c3-e2c8-41b6-ac34-0471f3e92e31</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>2e87df9f-6ea8-49e2-a8fa-78df7a77aadd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Operation</value>
         <variableId>efeae6f4-3f3e-4588-8af0-34464c4bba6a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ffa7487-f9f3-4b2a-9f86-0246012527f7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7e845faf-e890-4be9-baa3-f07c4dba1c71</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-AddJobFiles</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea55ab9f-206e-4fcf-9ae0-7848cbada80d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea661e7b-c276-42ef-a6c9-1c1ef53f2265</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73d599e9-d250-4bbc-8dc9-b8509e150c37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acd0c7cf-20ad-4071-a100-4a42f1e373db</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b1c73871-9c46-4945-8946-10b98fbaad55</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-AddJobScriptOption</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64ee1de1-1828-4d77-becb-8baf24e6e6ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1dd6665d-d333-4782-aad2-e1ca7324e28b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81884a8a-59c5-4af6-bb63-42db2be49040</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d6db54c-3469-4145-9d4e-a9761c738769</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4597ada2-27be-4cf2-95ed-09cd1aa0ac96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4501daa1-5d8a-4a59-b977-3109d0847ebe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0a7aec1-e16f-470f-b0f2-8b6360f0599c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7cbcb672-983b-43b0-bd2b-c56870a757ed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>365bc496-2a6c-4edb-852f-22b91da13358</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission_LeaveForm</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>19255bed-729c-4d0d-90e4-0f1ff3b3ae65</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>5-7</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForJobMonitoringGenericOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>19255bed-729c-4d0d-90e4-0f1ff3b3ae65</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>eafa6e12-0135-42fc-b1ff-a3f118a8a163</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7719920b-c14d-43fe-a629-bcb6b8101040</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>19255bed-729c-4d0d-90e4-0f1ff3b3ae65</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>005889aa-cf57-4be6-a956-bb131f6725ca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8f12ec96-380e-4798-86a2-8beae4c67665</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/MultipleJobSubmissions</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53d74077-eef0-44bf-a79a-ebb3b3690ba9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d34d24f-5e83-48ff-881f-4d9620e2e4c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc913d2d-7bc7-4ca8-a5ec-62e6669bdb3e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2cc9cbca-96b5-4742-a811-833a0d9bd9c9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-FileViewerOps</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>33adcdf3-a21f-4738-8030-c45f1488fdcb</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>7-12</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForFileViewer</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23b5d174-8326-4309-a461-a3a8b349eae4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>33adcdf3-a21f-4738-8030-c45f1488fdcb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FileName</value>
         <variableId>9b065ca7-abb9-4e53-9e42-92fff2b43874</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>33adcdf3-a21f-4738-8030-c45f1488fdcb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>c398326f-2040-448d-b714-a3071a0cdb4e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9bfd2275-d015-4425-85f4-42fe0a1e3d40</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>33adcdf3-a21f-4738-8030-c45f1488fdcb</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>33e3f1bb-053e-464d-a46d-f795250201eb</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
