#---1----|----2----|----3----|----4----|----5----|----6----|----7----|----8----|----9----|---10----|
/MAT/HYD_JCOOK/1
Copper
#              RHO_I
                8.96
#                 E                   nu
                1.24                 .35
#                  A                   B                   n              epsmax              sigmax
                9E-4              .00292                 .31                   0               .0066
#               Pmin
               -1E30
#                  C           EPS_DOT_0                   M               Tmelt               Tmax
                .025                1E-6                1.09                1656                1E30
#              RHOCP
            3.461E-5
/EOS/GRUNEISEN/1
Copper
#                  C                  S1                  S2                  S3
                .394               1.489                   0                   0
#             GAMMA0               ALPHA                  E0               RHO_0
                1.97                 .47                   0                8.96
#---1----|----2----|----3----|----4----|----5----|----6----|----7----|----8----|----9----|---10----|
/MAT/JWL/2
TNT
#              RHO_I
                1.63
#                  A                   B                  R1                  R2               OMEGA
              3.7121               .0323                4.15                 .95                  .3
#                  D                P_CJ                  E0                Eadd   I_BFRAC
                .693                 .21                 .07                   0         0
#---1----|----2----|----3----|----4----|----5----|----6----|----7----|----8----|----9----|---10----|
/PROP/SOLID/1
Solid1
#   Isolid    Ismstr               Icpre               Inpts    Itetra    Iframe                  dn
         0         0                   0                   0         0         0                   0
#                q_a                 q_b                   h            LAMBDA_V                MU_V
                   0                   0                   0                   0                   0
#             dt_min   istrain      IHKT
                   0         0         0
#---1----|----2----|----3----|----4----|----5----|----6----|----7----|----8----|----9----|---10----|
/PROP/SOLID/2
Solid2
#   Isolid    Ismstr               Icpre               Inpts    Itetra    Iframe                  dn
         0         0                   0                   0         0         0                   0
#                q_a                 q_b                   h            LAMBDA_V                MU_V
                   0                   0                   0                   0                   0
#             dt_min   istrain      IHKT
                   0         0         0
#---1----|----2----|----3----|----4----|----5----|----6----|----7----|----8----|----9----|---10----|
#ENDDATA