<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>MultiFiles</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>22c6c816-6318-450f-863f-8e5911dde05e</testSuiteGuid>
   <testCaseLink>
      <guid>9ff9cf19-7d6c-4161-8556-11ca453d1073</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/FilesModule/MultiFileOperations</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>c8a6f8e8-a3eb-4572-8aed-a950fd474b1e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForFileOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>c8a6f8e8-a3eb-4572-8aed-a950fd474b1e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FileName</value>
         <variableId>6422f61a-59e5-4498-a9c7-aed432c255a5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c8a6f8e8-a3eb-4572-8aed-a950fd474b1e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>fbd214bf-d998-46fb-956c-96b9951450fa</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>c8a6f8e8-a3eb-4572-8aed-a950fd474b1e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Operation</value>
         <variableId>3c621b68-f5ca-4437-875c-7b8b34a301f4</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
