<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Preferences</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>353cf494-61eb-4252-8eee-70d002b82eb4</testSuiteGuid>
   <testCaseLink>
      <guid>8fa5098d-f38a-4250-811f-0dc47e46892d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Preferences/Set_Preferences</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>7d394bde-79e6-4d97-a0a2-ffc440bcaa5b</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForPreferences</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>7d394bde-79e6-4d97-a0a2-ffc440bcaa5b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>20e66ddf-642f-491a-b46e-0d3dc565bf8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7d394bde-79e6-4d97-a0a2-ffc440bcaa5b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>4611fa3d-9817-4318-9699-09323a3d16ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>7d394bde-79e6-4d97-a0a2-ffc440bcaa5b</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>preference</value>
         <variableId>8c467d1f-9c4c-493c-a375-d9145f840bda</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71b6bb43-2854-4a87-80e8-e8a6cc55b8f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a94cf29-3aca-457a-8b05-cbec1a213170</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>003edf9a-5cd2-49e7-b7ef-cf2adf5857a1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>630400d7-1a60-442c-afcd-0566c0a50cbe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80fb4bcc-6ac6-46ae-b1f3-d80a3cca2ee6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
