<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TestCases2021.1.1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>0f759cf3-899a-469d-a6be-751d27eeb9c0</testSuiteGuid>
   <testCaseLink>
      <guid>2f3c3e69-8373-4d3b-8e47-814738577ae0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/XRepeated_TC/Folder2021.1.1/Application_Name</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da95bcdd-96e2-480a-8cb5-1895a5b904b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e523dd49-30f9-4e4a-962c-6b237d006e42</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d22b7814-3737-4001-9355-099ce0589658</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/XRepeated_TC/Folder2021.1.1/App_Composer</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4fd17f9e-9d4f-412f-aec6-a8a9260936e2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28ea9b68-260f-4115-b7f9-9e3f7ec10ff0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>092d99c9-8080-4b82-a7b3-5554cc47e61d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/XRepeated_TC/Folder2021.1.1/JobSubmission_ShowAll</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e571ef8b-aa9f-49a8-af52-156d66962f76</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18519a09-984f-40c9-8639-c8d7b4502c2b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5cbeed2-37e7-4a0d-beb2-a70355ad502c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a057abe7-9355-47dc-a192-0e9fe8c12022</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e06f69f-d533-4c76-bb3d-9a88faed5f47</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e5d9090-f156-44c9-bc64-17085bb5ceca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b152a84d-a51d-4dd7-8302-058135d93961</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
