<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>JobSubmissionModule</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>c8059532-5217-49a5-a95c-761bac3ba85b</testSuiteGuid>
   <testCaseLink>
      <guid>64405d6e-4c82-4dd1-881a-bf07487ebfb9</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>dbd15a3e-d158-4bc2-a1f4-30bfc14bedae</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForJS-Latest</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>dbd15a3e-d158-4bc2-a1f4-30bfc14bedae</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>AppName</value>
         <variableId>26fbd4fc-965f-401e-a5c4-6fb431cd201b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>dbd15a3e-d158-4bc2-a1f4-30bfc14bedae</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>InputFile</value>
         <variableId>e9d3b8c0-f5fe-46e9-a72e-1a22d9f59c79</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>dbd15a3e-d158-4bc2-a1f4-30bfc14bedae</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>518a544d-f5ac-448a-acfc-06b909661db8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>dbd15a3e-d158-4bc2-a1f4-30bfc14bedae</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FileArg</value>
         <variableId>e66844e3-6552-46e7-8030-77932e3be780</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>dbd15a3e-d158-4bc2-a1f4-30bfc14bedae</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Mode</value>
         <variableId>ea501a92-5498-450d-afcd-13bfabb19fdd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>dbd15a3e-d158-4bc2-a1f4-30bfc14bedae</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ToChange</value>
         <variableId>816d5f07-afb8-4c81-9dde-4af3c892b31c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>dbd15a3e-d158-4bc2-a1f4-30bfc14bedae</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ChangeValue</value>
         <variableId>ea3c8f43-9d3d-4606-b294-b1768dbf277b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4611ab03-3b21-4bdb-a558-d03398d2333b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-FileOperations</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>55fe4f85-8ace-4335-a980-7076d8503691</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForJobSubmissionFileOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>295020a0-90c1-43b3-b6b1-8be5bdf98484</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>55fe4f85-8ace-4335-a980-7076d8503691</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FileName</value>
         <variableId>d7386246-6246-4cc7-b688-3ceed1d43158</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>55fe4f85-8ace-4335-a980-7076d8503691</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>eaebe514-d89a-4eb9-9d9f-8d87bb9fbb58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>55fe4f85-8ace-4335-a980-7076d8503691</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Operation</value>
         <variableId>62f61e34-294a-4077-afd6-a99d73244bdb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2452730a-fb63-4365-92a2-2ba74197dafc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7e20caf-abd7-45d3-b8eb-a35fe4e133fb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>10dd1fc7-0ce9-4195-ae0e-d6db1c036db3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/XRepeated_TC/JobSubmission-FileOperations-Topmenuicons</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a0501715-fccd-4d76-8722-f3925ce43985</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-4</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForJobSubmissionFileOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>120ba62f-cb20-420f-b9ed-bc964b7eaab5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a0501715-fccd-4d76-8722-f3925ce43985</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FileNameIcon</value>
         <variableId>69e965b4-ec08-4e83-a907-9aa3bb51eb9d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a0501715-fccd-4d76-8722-f3925ce43985</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>01885c6a-c4fa-47e2-b0ef-08c44571cc02</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a0501715-fccd-4d76-8722-f3925ce43985</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>IconOperation</value>
         <variableId>22302168-4dbd-4a3c-81bd-627834fe4f4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3294d234-7ac9-4e40-9586-bb788fe78fb8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c32bb7da-d3b6-4122-9ce7-00f93cac6d04</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/XRepeated_TC/JobSubmission-FolderOperations-Topmenuicons</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ff3bcf4a-c4ee-4d91-b2d5-0667d00d7820</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-4</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForJobSubmission-FolderOps</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>282533ac-7186-412e-b328-346236da8b00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ff3bcf4a-c4ee-4d91-b2d5-0667d00d7820</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FolderName</value>
         <variableId>5ea127d8-b300-4e17-810d-e61fa8333209</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ff3bcf4a-c4ee-4d91-b2d5-0667d00d7820</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>4de6a06a-99da-4e29-b4a7-02d6fbe53d76</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ff3bcf4a-c4ee-4d91-b2d5-0667d00d7820</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>IconOperation</value>
         <variableId>19c30876-5316-4840-9428-1ba360cec6de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76a40af3-e743-477e-b0f5-fc543856d43c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5977fe42-138b-4ddf-ac48-a15f439283c8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-VerifyLabel</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8b4b244-4333-4de5-9a0f-fd535ae77ba6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>599df223-1449-4c1b-9b52-6bcc122ef427</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac8b30c6-a5ee-4ad6-bea9-46a99d790ec3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>375dab6b-3fa4-4f54-9f33-928bbbe09625</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-InvalidPath</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b852c29-2a95-473d-955d-ed3bbe631419</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94f63a41-04d8-46ce-a37b-ae2b3074fd43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfa17c7d-5dd5-4bf7-9c99-aed96fe86e0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ee91afc-9df8-4d4f-86a7-9c1144499de1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0a277087-bfca-4cd4-b07b-491c370d9b6a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission_LeaveForm</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>cb4be9cf-215e-496e-8459-536a3af8c9d9</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>5-7</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForJobMonitoringGenericOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>cb4be9cf-215e-496e-8459-536a3af8c9d9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>eafa6e12-0135-42fc-b1ff-a3f118a8a163</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7719920b-c14d-43fe-a629-bcb6b8101040</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>cb4be9cf-215e-496e-8459-536a3af8c9d9</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>005889aa-cf57-4be6-a956-bb131f6725ca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>313b1324-604c-4f7b-82e0-1ae6148235bc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission_Reset</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>05809abe-3c2a-4959-9487-d5ff900be00f</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>8-10</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForJobMonitoringGenericOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>05809abe-3c2a-4959-9487-d5ff900be00f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>9d060f0b-9277-43e9-8c05-317c9ed897bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d040abb9-7351-4685-b440-05d8801dd4bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>05809abe-3c2a-4959-9487-d5ff900be00f</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>debc6772-d8e4-4397-a148-25d8cf3db661</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d68a528c-cade-4cca-b240-49ca1423bca2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/MultipleJobSubmissions</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53d74077-eef0-44bf-a79a-ebb3b3690ba9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d34d24f-5e83-48ff-881f-4d9620e2e4c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc913d2d-7bc7-4ca8-a5ec-62e6669bdb3e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>66fef6b7-032b-4450-8ddc-a863acf2a43c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/XRepeated_TC/JobSubmission_Helpbox_Enabled</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>680b0924-9886-4c40-b374-1867e98cdce3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4154522b-93ea-42f6-b3a5-f0ce4a87c87e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>826fc129-a48b-47db-a772-1cdac51e73fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae327a85-f5a3-46a6-bbed-025090fd2145</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe4b64c5-adf4-4325-b4d2-2572b9ccea22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>edd19741-461c-4e09-9a05-854c2ccc88ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc671ec7-8c19-4a0b-a271-9357bb172c2c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>114964af-6579-49fc-a8c5-688111a4db1a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/XRepeated_TC/JobSubmission_Helpbox_Disabled</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5db5f97f-7c3f-46a5-9413-2c85d232247c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>688e3f36-1d89-4e42-bfad-be5a3bb54374</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>190ae24b-12f7-4578-8d71-8a6b73beed19</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acaa2c69-65ab-4e96-8c8e-c2bb86950a2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb41cccf-9ba4-425d-a4a3-ed2e62fd39ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40b466ff-5064-4ec3-9e88-d5498d7717cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c954eee0-071d-4262-a7d7-edc6f53162c6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>08fcc9f9-5c56-4e64-bd9d-48aac86f7066</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/XRepeated_TC/JobSubmissionForLastSubmitted</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2165b182-636d-4b7f-ade2-161fca571166</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc34a078-3b76-4c35-9aca-e5bdde596154</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8593a4b9-9f88-428e-ba17-b836e798acf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e5d3486-4f6d-4c60-b9f7-f852e8083cf1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6ecc3a3-627b-4125-86fb-cb2431021897</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d935056-a60a-4f76-a4d1-527bbd6f770d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3c1226f-d56d-4cdf-ab0d-cd98ce0d3fa2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b0ea0f94-450d-4f1e-8e2e-d8a125a1ec09</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-AddJobScriptOption</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64ee1de1-1828-4d77-becb-8baf24e6e6ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1dd6665d-d333-4782-aad2-e1ca7324e28b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81884a8a-59c5-4af6-bb63-42db2be49040</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d6db54c-3469-4145-9d4e-a9761c738769</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4597ada2-27be-4cf2-95ed-09cd1aa0ac96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4501daa1-5d8a-4a59-b977-3109d0847ebe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0a7aec1-e16f-470f-b0f2-8b6360f0599c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7cbcb672-983b-43b0-bd2b-c56870a757ed</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
