<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>JSFileOps</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>bf19985f-d238-4709-9542-973ba388574b</testSuiteGuid>
   <testCaseLink>
      <guid>7c2060f4-e812-439e-b73a-bf7da80ede90</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/MultipleJobSubmissions</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53d74077-eef0-44bf-a79a-ebb3b3690ba9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d34d24f-5e83-48ff-881f-4d9620e2e4c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc913d2d-7bc7-4ca8-a5ec-62e6669bdb3e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>60fc8295-97d4-4e81-a11c-c1bf7c1ef1be</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-FileOperations</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>6cca387c-ae79-43df-af08-1d94db925586</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForJobSubmissionFileOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>295020a0-90c1-43b3-b6b1-8be5bdf98484</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6cca387c-ae79-43df-af08-1d94db925586</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FileName</value>
         <variableId>d7386246-6246-4cc7-b688-3ceed1d43158</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6cca387c-ae79-43df-af08-1d94db925586</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>eaebe514-d89a-4eb9-9d9f-8d87bb9fbb58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>6cca387c-ae79-43df-af08-1d94db925586</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Operation</value>
         <variableId>62f61e34-294a-4077-afd6-a99d73244bdb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2452730a-fb63-4365-92a2-2ba74197dafc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f7e20caf-abd7-45d3-b8eb-a35fe4e133fb</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>087d050a-834e-4c93-8679-3aa572c9d9cb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/XRepeated_TC/JobSubmission-FileOperations-Topmenuicons</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>17cf1cbb-b7b5-4057-b63f-9f8b2737ee58</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value>1-5</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForJobSubmissionFileOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>120ba62f-cb20-420f-b9ed-bc964b7eaab5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>17cf1cbb-b7b5-4057-b63f-9f8b2737ee58</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FileName</value>
         <variableId>69e965b4-ec08-4e83-a907-9aa3bb51eb9d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>17cf1cbb-b7b5-4057-b63f-9f8b2737ee58</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>01885c6a-c4fa-47e2-b0ef-08c44571cc02</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>17cf1cbb-b7b5-4057-b63f-9f8b2737ee58</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>IconOperation</value>
         <variableId>22302168-4dbd-4a3c-81bd-627834fe4f4c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3294d234-7ac9-4e40-9586-bb788fe78fb8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5b4770fe-35f2-49d1-aa13-fa1f189dd0ba</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/XRepeated_TC/JobSubmission-FolderOperations-Topmenuicons</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>dd73495e-5624-4a23-9806-657e63bff286</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value>1-4</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForJobSubmission-FolderOps</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>282533ac-7186-412e-b328-346236da8b00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>dd73495e-5624-4a23-9806-657e63bff286</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FolderName</value>
         <variableId>5ea127d8-b300-4e17-810d-e61fa8333209</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>dd73495e-5624-4a23-9806-657e63bff286</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>4de6a06a-99da-4e29-b4a7-02d6fbe53d76</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>dd73495e-5624-4a23-9806-657e63bff286</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>IconOperation</value>
         <variableId>19c30876-5316-4840-9428-1ba360cec6de</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>76a40af3-e743-477e-b0f5-fc543856d43c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3d6c6aa3-018c-49b5-b1e7-c4d15b7453ca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-InvalidPath</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b852c29-2a95-473d-955d-ed3bbe631419</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94f63a41-04d8-46ce-a37b-ae2b3074fd43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfa17c7d-5dd5-4bf7-9c99-aed96fe86e0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ee91afc-9df8-4d4f-86a7-9c1144499de1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4dc4abda-ffae-474b-8b30-657098409991</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/XRepeated_TC/JobSubmission_Helpbox_Disabled</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5db5f97f-7c3f-46a5-9413-2c85d232247c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>688e3f36-1d89-4e42-bfad-be5a3bb54374</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>190ae24b-12f7-4578-8d71-8a6b73beed19</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acaa2c69-65ab-4e96-8c8e-c2bb86950a2a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bb41cccf-9ba4-425d-a4a3-ed2e62fd39ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40b466ff-5064-4ec3-9e88-d5498d7717cf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c954eee0-071d-4262-a7d7-edc6f53162c6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3d0fe48d-3f8c-4a6f-98cc-2edaa8da6a72</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-VerifyLabel</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>0452b09a-2c08-4d5c-ba11-b1abde3ea862</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>11-12</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForJobMonitoringGenericOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8b4b244-4333-4de5-9a0f-fd535ae77ba6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0452b09a-2c08-4d5c-ba11-b1abde3ea862</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>599df223-1449-4c1b-9b52-6bcc122ef427</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>0452b09a-2c08-4d5c-ba11-b1abde3ea862</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>ac8b30c6-a5ee-4ad6-bea9-46a99d790ec3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>51d4bc8d-b456-424c-b30b-296ed2fc4553</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-switchApplication</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f5fc2ade-2b0d-4f8c-9c81-250fff92cae5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6413bb5-8219-4755-a651-79cc0c9b129f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d136fd6a-f3fa-44c6-bfda-d4211751b61f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>11230f5d-2647-4379-8eb7-5ddb6672c072</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e50dac30-7a76-48be-b01d-426bbf80bc96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>622ae497-c74e-472f-972d-2996e7120e60</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>22fde961-5a7d-4c8d-acf8-8ec4b585ad13</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/XRepeated_TC/JobSubmission_Helpbox_Enabled</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>680b0924-9886-4c40-b374-1867e98cdce3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4154522b-93ea-42f6-b3a5-f0ce4a87c87e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>826fc129-a48b-47db-a772-1cdac51e73fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae327a85-f5a3-46a6-bbed-025090fd2145</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe4b64c5-adf4-4325-b4d2-2572b9ccea22</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>edd19741-461c-4e09-9a05-854c2ccc88ee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bc671ec7-8c19-4a0b-a271-9357bb172c2c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e7df1ab6-fd52-45c5-821c-74d6d2b61609</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission_LeaveForm</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4e3fa02d-095a-446d-81a7-a728e667e5fd</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>5-7</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForJobMonitoringGenericOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>4e3fa02d-095a-446d-81a7-a728e667e5fd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>eafa6e12-0135-42fc-b1ff-a3f118a8a163</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7719920b-c14d-43fe-a629-bcb6b8101040</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4e3fa02d-095a-446d-81a7-a728e667e5fd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>005889aa-cf57-4be6-a956-bb131f6725ca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a8aaa38b-e7ab-4eed-b1df-7c087e7bd6bd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission_Reset</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4a0d44a6-5757-4036-a22e-9c06c90e3e3d</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>8-10</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForJobMonitoringGenericOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>4a0d44a6-5757-4036-a22e-9c06c90e3e3d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>9d060f0b-9277-43e9-8c05-317c9ed897bd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d040abb9-7351-4685-b440-05d8801dd4bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4a0d44a6-5757-4036-a22e-9c06c90e3e3d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>debc6772-d8e4-4397-a148-25d8cf3db661</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0fae09fe-20bd-485f-a313-5e68d740e23a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmissionForLastSubmitted</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4cb43813-67a3-4161-b8ed-6837214c3566</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>13-14</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForJobMonitoringGenericOperations</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2165b182-636d-4b7f-ade2-161fca571166</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc34a078-3b76-4c35-9aca-e5bdde596154</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4cb43813-67a3-4161-b8ed-6837214c3566</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>8593a4b9-9f88-428e-ba17-b836e798acf9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e5d3486-4f6d-4c60-b9f7-f852e8083cf1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d6ecc3a3-627b-4125-86fb-cb2431021897</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3d935056-a60a-4f76-a4d1-527bbd6f770d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3c1226f-d56d-4cdf-ab0d-cd98ce0d3fa2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4cb43813-67a3-4161-b8ed-6837214c3566</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>0d0853fe-9935-4957-956d-2f65728efe35</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1d464ced-a2a4-4303-a295-d4ba9e350b92</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-AddJobScriptOption</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64ee1de1-1828-4d77-becb-8baf24e6e6ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1dd6665d-d333-4782-aad2-e1ca7324e28b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81884a8a-59c5-4af6-bb63-42db2be49040</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d6db54c-3469-4145-9d4e-a9761c738769</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4597ada2-27be-4cf2-95ed-09cd1aa0ac96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4501daa1-5d8a-4a59-b977-3109d0847ebe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0a7aec1-e16f-470f-b0f2-8b6360f0599c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7cbcb672-983b-43b0-bd2b-c56870a757ed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7d26efc6-8c56-4d38-95d0-4527217d2a44</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-AddJobFiles</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea55ab9f-206e-4fcf-9ae0-7848cbada80d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ea661e7b-c276-42ef-a6c9-1c1ef53f2265</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>73d599e9-d250-4bbc-8dc9-b8509e150c37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acd0c7cf-20ad-4071-a100-4a42f1e373db</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
