<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>NewRuns</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>c4c68cf0-9eb4-4f17-b43e-e5dec91fb27d</testSuiteGuid>
   <testCaseLink>
      <guid>955ac737-9161-42f1-9c35-a78dd1762fd6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/JobMonitoring/Jobdetailspage_context menu</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>8997dcc6-0e14-4456-87e8-3c380eb1d8ea</id>
         <iterationEntity>
            <iterationType>RANGE</iterationType>
            <value>1-29</value>
         </iterationEntity>
         <testDataId>Data Files/TestDataForJobDetails</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>8997dcc6-0e14-4456-87e8-3c380eb1d8ea</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>JobState</value>
         <variableId>4a636c84-6f6f-4327-bc88-0f06ed57c48e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8997dcc6-0e14-4456-87e8-3c380eb1d8ea</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>JobAction</value>
         <variableId>b07c6840-6124-403c-88c8-73fd685aac37</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8997dcc6-0e14-4456-87e8-3c380eb1d8ea</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>95be6fc3-cb4f-4e7e-aee7-4913d254fd84</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>8997dcc6-0e14-4456-87e8-3c380eb1d8ea</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>aa175b05-32fc-49ca-a330-8cfe38b2837c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0db99bb0-d415-4082-8ef3-cb4a706388aa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Upload/RunningFolder_jobspage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e5912aa-44cb-4a2a-8cbd-d878986a8cb8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3dfb89e-d66e-42d0-bfd7-4bbd555d0c58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b559ba8-93b4-4f35-8694-c51dea26e300</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>098e6013-1c93-4f47-8b26-69214f7e665a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f4f0255b-a5e3-4845-a674-e0276c099011</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Upload/Uploadfile_replace_existingfile</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2d942e0-ef05-422f-8197-c27d84a551af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2402d5c3-9454-46b4-91d5-4ee0725f4733</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c26a9d81-7e43-4dcf-b37b-d3b8845315ca</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Upload/Uploadfile_uncompress</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23c75d3e-c92d-4605-aea2-cab55897792c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbf9d73d-969b-4d15-90d6-26b5b76612ad</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3e4ff287-dfac-49d5-8e12-920b0bf6aa61</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Upload/Uploadfile_verify_unzipmessage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ea9fce1-f358-4cdd-8ebc-db0f6441f4ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb4e129b-d74a-4fc3-805c-55abeb31584a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3503d7ce-ae19-4b85-ac7a-c893897f9038</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-VerifyLabel</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a8b4b244-4333-4de5-9a0f-fd535ae77ba6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>599df223-1449-4c1b-9b52-6bcc122ef427</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac8b30c6-a5ee-4ad6-bea9-46a99d790ec3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6a26780a-d6b0-42b8-9fa7-51f340fe92fa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-AddJobScriptOption</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64ee1de1-1828-4d77-becb-8baf24e6e6ed</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1dd6665d-d333-4782-aad2-e1ca7324e28b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81884a8a-59c5-4af6-bb63-42db2be49040</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9d6db54c-3469-4145-9d4e-a9761c738769</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4597ada2-27be-4cf2-95ed-09cd1aa0ac96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4501daa1-5d8a-4a59-b977-3109d0847ebe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f0a7aec1-e16f-470f-b0f2-8b6360f0599c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7cbcb672-983b-43b0-bd2b-c56870a757ed</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>333f5f7d-596c-46d6-a30c-7b7f067f0e1e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission-InvalidPath</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5b852c29-2a95-473d-955d-ed3bbe631419</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>94f63a41-04d8-46ce-a37b-ae2b3074fd43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfa17c7d-5dd5-4bf7-9c99-aed96fe86e0d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ee91afc-9df8-4d4f-86a7-9c1144499de1</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>38e65859-33fa-4203-93ee-690d080ba28d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Generic_Actions/Generic_Actions</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e47b77ef-b2e7-4db0-8e59-d0281e610867</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af386d66-71c7-4cf3-9748-0abd139a3e50</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2baedf90-60fa-4fcc-bd63-d0af7ed2a94d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Preferences/Set_Preferences</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>bdf4a9bb-0104-4ac0-b4d6-55ca9025ca8d</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/TestDataForPreferences</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>bdf4a9bb-0104-4ac0-b4d6-55ca9025ca8d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>20e66ddf-642f-491a-b46e-0d3dc565bf8c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bdf4a9bb-0104-4ac0-b4d6-55ca9025ca8d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>userChoice</value>
         <variableId>4611fa3d-9817-4318-9699-09323a3d16ae</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bdf4a9bb-0104-4ac0-b4d6-55ca9025ca8d</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>preference</value>
         <variableId>8c467d1f-9c4c-493c-a375-d9145f840bda</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>71b6bb43-2854-4a87-80e8-e8a6cc55b8f7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4a94cf29-3aca-457a-8b05-cbec1a213170</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>003edf9a-5cd2-49e7-b7ef-cf2adf5857a1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>630400d7-1a60-442c-afcd-0566c0a50cbe</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>80fb4bcc-6ac6-46ae-b1f3-d80a3cca2ee6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
