<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CheckBox_Select_All</name>
   <tag></tag>
   <elementGuidId>9c842882-9fef-4725-bd52-ba66bcac1b0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='ag-header-select-all ag-labeled ag-label-align-right ag-checkbox']//span[@class='ag-icon ag-icon-checkbox-unchecked']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;fileviewer_filelist_table&quot;)/div[@class=&quot;white-theme&quot;]/div[@class=&quot;react-grid-Container&quot;]/div[@class=&quot;react-grid-Main&quot;]/div[@class=&quot;react-grid-Grid&quot;]/div[@class=&quot;react-grid-Header&quot;]/div[@class=&quot;react-grid-HeaderRow&quot;]/div[1]/div[@class=&quot;react-grid-HeaderCell react-grid-HeaderCell--locked&quot;]/div[@class=&quot;react-grid-checkbox-container checkbox-align&quot;]/label[@class=&quot;react-grid-checkbox-label&quot;][count(. | //label[@for = 'select-all-checkbox-FILE_VIEWER' and @class = 'react-grid-checkbox-label']) = count(//label[@for = 'select-all-checkbox-FILE_VIEWER' and @class = 'react-grid-checkbox-label'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>select-all-checkbox-FILE_VIEWER</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>react-grid-checkbox-label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fileviewer_filelist_table&quot;)/div[@class=&quot;white-theme&quot;]/div[@class=&quot;react-grid-Container&quot;]/div[@class=&quot;react-grid-Main&quot;]/div[@class=&quot;react-grid-Grid&quot;]/div[@class=&quot;react-grid-Header&quot;]/div[@class=&quot;react-grid-HeaderRow&quot;]/div[1]/div[@class=&quot;react-grid-HeaderCell react-grid-HeaderCell--locked&quot;]/div[@class=&quot;react-grid-checkbox-container checkbox-align&quot;]/label[@class=&quot;react-grid-checkbox-label&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fileviewer_filelist_table']/div/div/div/div/div/div/div/div[6]/div/label</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='File Size'])[1]/following::label[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Owner'])[1]/following::label[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lag6elem_0000_1573466375914'])[1]/preceding::label[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bhuvana'])[2]/preceding::label[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label</value>
   </webElementXpaths>
</WebElementEntity>
