<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FilesDelete_img</name>
   <tag></tag>
   <elementGuidId>226674ff-77da-4944-88a2-9beb70670dac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@class='additional_file_options pull-right']//div[@id='delete_icon']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'delete_icon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a1bf1f1a-6b18-4a05-8558-8ac260e7ce54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/unity_delete.6169b9f2.svg</value>
      <webElementGuid>032c2b5d-5930-4f6f-bc87-75e3ef971f4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>delete_icon</value>
      <webElementGuid>f5a2b44d-49ef-4aa6-80a8-2529463fc99a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;delete_icon&quot;)/img[1]</value>
      <webElementGuid>3748b30b-eaa1-465e-85d5-c9a037e0f362</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='delete_icon']/img</value>
      <webElementGuid>ab4cfb24-5f2c-43fa-80cd-7feaee4c4636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Files'])[2]/following::img[4]</value>
      <webElementGuid>94f03965-7b57-4ff1-90e0-fdf39115be9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Myfolder1'])[1]/following::img[4]</value>
      <webElementGuid>68a726c5-8285-4ffd-8d72-d5876e57acee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Upload File'])[1]/preceding::img[2]</value>
      <webElementGuid>5a4c445b-bd1b-4a65-815a-4098aa13deea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='delete_icon']</value>
      <webElementGuid>660045e7-a013-4aa1-8aa9-abf8464bb03f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/img</value>
      <webElementGuid>9e777cda-206f-4d42-bf28-4ab689bb03fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
