<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>UploadFolderBtn</name>
   <tag></tag>
   <elementGuidId>ccc2e1fb-e9ad-4d6c-80bb-e3db8de010e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[@id = 'folder_upload_element_dirview']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87f4d2e8-f25a-4175-b66e-3e5dcd28af18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>folder_upload_element_dirview</value>
      <webElementGuid>a4915a9d-4b4e-41fe-9246-2db4afc8be19</webElementGuid>
   </webElementProperties>
</WebElementEntity>
