<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Uploadbtn_File</name>
   <tag></tag>
   <elementGuidId>815c4416-ea7f-47e0-8da2-a5467ef7e559</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id=&quot;upload_folder_button_parent&quot;]//div[@id=&quot;dir_folder_menu&quot;]//span[contains(text(),&quot;File&quot;)]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
