<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Btn_Notifiction3</name>
   <tag></tag>
   <elementGuidId>a01d3863-cb1d-480c-b90d-b4f44285ee59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id = 'app_notify_menu' and @title = 'Notifications']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>3753066b-d05b-4ff4-bcb9-28ff4d38a764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>app_notify_menu</value>
      <webElementGuid>3a72ebe4-69f9-4845-8395-5354ece83259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Notifications</value>
      <webElementGuid>cb89bf5d-e2e1-4c53-b526-7f15a70944ef</webElementGuid>
   </webElementProperties>
</WebElementEntity>
