<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ThemeColour</name>
   <tag></tag>
   <elementGuidId>31d1252f-ef96-411e-a67d-071080c53a26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[(contains(text(), 'White') or contains(., 'White'))]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>60b3c05e-30d9-40b1-b655-75ec661d70d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>White</value>
      <webElementGuid>388c3af0-c146-4345-abc4-cfe503ca4a5c</webElementGuid>
   </webElementProperties>
</WebElementEntity>
