<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>JobSubmission</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>8cfdd852-3168-4a44-b608-f186cd887fe6</testSuiteGuid>
   <testCaseLink>
      <guid>9664a690-ae89-4da4-8d27-b6ed156961c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/JobSubmission/JobSubmission</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>bb74da93-4c6e-4eb0-8cac-de53d70ee2ba</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value>53</value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataForJS-Latest</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>bb74da93-4c6e-4eb0-8cac-de53d70ee2ba</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>AppName</value>
         <variableId>26fbd4fc-965f-401e-a5c4-6fb431cd201b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bb74da93-4c6e-4eb0-8cac-de53d70ee2ba</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>InputFile</value>
         <variableId>e9d3b8c0-f5fe-46e9-a72e-1a22d9f59c79</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bb74da93-4c6e-4eb0-8cac-de53d70ee2ba</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>518a544d-f5ac-448a-acfc-06b909661db8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bb74da93-4c6e-4eb0-8cac-de53d70ee2ba</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>FileArg</value>
         <variableId>e66844e3-6552-46e7-8030-77932e3be780</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bb74da93-4c6e-4eb0-8cac-de53d70ee2ba</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Mode</value>
         <variableId>ea501a92-5498-450d-afcd-13bfabb19fdd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bb74da93-4c6e-4eb0-8cac-de53d70ee2ba</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ToChange</value>
         <variableId>816d5f07-afb8-4c81-9dde-4af3c892b31c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>bb74da93-4c6e-4eb0-8cac-de53d70ee2ba</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ChangeValue</value>
         <variableId>ea3c8f43-9d3d-4606-b294-b1768dbf277b</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
