<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>NewTestcaseAccessWeb</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>999a5500-6c9b-4317-9a73-276817a104ae</testSuiteGuid>
   <testCaseLink>
      <guid>5b08004f-a8ae-4ab1-bf8a-390523b16b14</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WindowTitle/BrowserVersion</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4601ff3c-2fec-4c45-a234-b1a99245f66f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f0de2683-9184-4dda-a94b-58fa23868366</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WindowTitle/GetWindowTitle</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>a154eedf-0d58-4776-a014-4bb71ea8c426</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Regression/TestDataAccessWeb</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7e16d2e-0b13-4e73-957e-8575c0bc254e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66aa9127-13ad-43ab-a072-53eea7e467e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>a154eedf-0d58-4776-a014-4bb71ea8c426</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>TestCaseName</value>
         <variableId>4e26fe06-f737-4bad-8a94-3ce18a62cbb4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>32ed20d1-8dca-4e69-8531-241f053a6b06</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3080d45e-d09d-41dd-9260-5c6b4f00d2ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>826205c1-167c-46ec-9ce3-1cdfc16899ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>98fa2418-ff60-4297-8a4f-c8ccc94897e5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>51a03fe8-9eb7-47b5-ba1c-2477e7df969d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WindowTitle/JobApplicationFilterVerification</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b292f73-6e4e-44a1-afc8-5515f4bae6f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>89e76b7e-4494-4c6e-ba5e-4dc4c0ebf02e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>af74ead0-ad1a-48e1-9136-865ab3d1a631</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2f81dc48-02c2-4203-b874-992fce0dd013</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cd788421-1c33-4b4f-99f4-9e64e9f135b6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/WindowTitle/JobColumnVerification</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b717dc8a-b8de-44cd-bde5-6c2f3419754b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92cfa93b-f45c-4806-b38e-d3069f59b16b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd27047a-f290-4db7-a132-87197302a1fb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c562e8d8-b57e-447b-a968-93b5d778e6ca</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
