<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>RunningFolderUploads</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>075247a2-dd30-4a4f-8402-87285a725e7f</testSuiteGuid>
   <testCaseLink>
      <guid>87993bdc-3186-4d03-962b-5c27d3271d9a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Upload/RunningFolder_jobspage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e5912aa-44cb-4a2a-8cbd-d878986a8cb8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3dfb89e-d66e-42d0-bfd7-4bbd555d0c58</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2b559ba8-93b4-4f35-8694-c51dea26e300</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>098e6013-1c93-4f47-8b26-69214f7e665a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3a923b93-bc32-48d5-abb0-30764054c2bf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Upload/Uploadfile_replace_existingfile</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c2d942e0-ef05-422f-8197-c27d84a551af</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2402d5c3-9454-46b4-91d5-4ee0725f4733</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f3572361-b16d-4c29-9796-2599030d480a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Upload/Uploadfile_uncompress</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>23c75d3e-c92d-4605-aea2-cab55897792c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cbf9d73d-969b-4d15-90d6-26b5b76612ad</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1e0674a7-ef4d-47e1-b98d-8be44dd9445d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Upload/Uploadfile_verify_unzipmessage</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4ea9fce1-f358-4cdd-8ebc-db0f6441f4ca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fb4e129b-d74a-4fc3-805c-55abeb31584a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
