<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Input_tab</name>
   <tag></tag>
   <elementGuidId>77e324c5-f30e-4db2-9164-9f98f1609d05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@id = 'app_input_tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>f2be23bd-a6ec-4771-9aab-74a582d4f173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>app_input_tab</value>
      <webElementGuid>c773e485-9e6f-40eb-9824-089ccd008fcc</webElementGuid>
   </webElementProperties>
</WebElementEntity>
