<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Output_tab</name>
   <tag></tag>
   <elementGuidId>bf62c625-80ab-4a07-877e-6910c8f730d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[@id = 'app_output_tab']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>1588658f-5b36-471a-bee8-cef9f8cd32cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>app_output_tab</value>
      <webElementGuid>75953a06-eef7-4d9e-973d-9c3761636fbd</webElementGuid>
   </webElementProperties>
</WebElementEntity>
