<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>uploadbtn_Folder_Runningtab</name>
   <tag></tag>
   <elementGuidId>1631fa85-c8de-4445-bb13-c5dca6534cb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id=&quot;upload_folder_button_parent_running&quot;]//div[@id=&quot;dir_folder_menu&quot;]//span[contains(text(),&quot;Folder&quot;)]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
