<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>uploadbtn_File_Runningtab</name>
   <tag></tag>
   <elementGuidId>9bf6001f-2fcd-499e-916a-b6a4b9bbb946</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id=&quot;upload_folder_button_parent_running&quot;]//div[@id=&quot;dir_folder_menu&quot;]//span[contains(text(),&quot;File&quot;)]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
