<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Lable_JobName</name>
   <tag></tag>
   <elementGuidId>d14e7e6e-5e5f-4dd9-a844-f8565f364eff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='submission_job_name_label']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//label[@id = 'submission_job_name_label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submission_job_name_label</value>
   </webElementProperties>
</WebElementEntity>
