<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RequiredLabel</name>
   <tag></tag>
   <elementGuidId>96c5522b-bad9-4837-a0d4-4ec9f27f5834</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>submission_reqall_req_field</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//label[@id = 'submission_reqall_req_field']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submission_reqall_req_field</value>
   </webElementProperties>
</WebElementEntity>
