<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Verify_Jobscript</name>
   <tag></tag>
   <elementGuidId>61a3ebd3-72c4-4459-be54-f5e9e166f5c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@title='/stage/rohini/JobsModule/InputDeck/bar.fem']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(@title, 'JobsModule/InputDeck/bar.fem')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>JobsModule/InputDeck/bar.fem</value>
   </webElementProperties>
</WebElementEntity>
