<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Jobdetails_topmenu</name>
   <tag></tag>
   <elementGuidId>3d45de18-bc94-49f2-aff8-f233f03a6a36</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='job_detail_download_btn']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//button[@id = 'job_detail_download_btn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>job_detail_download_btn</value>
   </webElementProperties>
</WebElementEntity>
