<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>OutputFolder_File</name>
   <tag></tag>
   <elementGuidId>80949829-3f96-4a6a-9cc6-49390f4bebab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[(text() = 'bar.fem' or . = 'bar.fem')]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(text(),'bar.fem')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>bar.fem</value>
   </webElementProperties>
</WebElementEntity>
