<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Calendar_Icon_From_date</name>
   <tag></tag>
   <elementGuidId>252d9166-37f4-40b6-8a87-ec25ce9bb070</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@title = 'Select date' and @type = 'button']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>svg.rw-i-calendar</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;tabs&quot;]/div[@class=&quot;tabs__content&quot;]/div[@class=&quot;audit-dashboard&quot;]/div[@class=&quot;logs-filters&quot;]/div[@class=&quot;date-field-wrapper&quot;]/div[@class=&quot;theme-receiver date-field-container from-date-field&quot;]/div[@class=&quot;date-time-control&quot;]/div[@class=&quot;rw-date-picker rw-widget&quot;]/div[@class=&quot;rw-widget-picker rw-widget-container&quot;]/button[@class=&quot;rw-input-addon rw-picker-btn rw-btn&quot;]/svg[@class=&quot;rw-i-calendar&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>9450a141-02b4-4bfc-aa2f-ac078316a7ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5a37993c-8698-4a33-8ce1-c4397f84d757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>e83eb195-03bd-4682-aeab-24855dc45a4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentcolor</value>
      <webElementGuid>e934a5f5-6a32-4119-b175-ab663b27f39f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 448 512</value>
      <webElementGuid>0c5ca482-3ac7-4a73-b718-3c94f28c997e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rw-i-calendar</value>
      <webElementGuid>0272221d-577f-41e2-916a-bcb859062da1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>89e85bce-db73-466b-ae4d-92020b5149fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;tabs&quot;]/div[@class=&quot;tabs__content&quot;]/div[@class=&quot;audit-dashboard&quot;]/div[@class=&quot;logs-filters&quot;]/div[@class=&quot;date-field-wrapper&quot;]/div[@class=&quot;theme-receiver date-field-container from-date-field&quot;]/div[@class=&quot;date-time-control&quot;]/div[@class=&quot;rw-date-picker rw-widget&quot;]/div[@class=&quot;rw-widget-picker rw-widget-container&quot;]/button[@class=&quot;rw-input-addon rw-picker-btn rw-btn&quot;]/svg[@class=&quot;rw-i-calendar&quot;]</value>
      <webElementGuid>580b4d53-ba65-4986-a179-4aa52af5743b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From Date'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>4c5c1050-67bb-4638-b49a-9e46ed54fd1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export Data'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>53bc37a8-e43f-4473-a67d-86ac6b9709dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To Date'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>a2d2dcbe-6764-4b11-822a-a2cf291e9b5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Time'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>b475058c-394d-44a7-a087-088100df4594</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
