<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Label_NoSessionMsg</name>
   <tag></tag>
   <elementGuidId>7742e6f8-3963-4856-b7d0-3689bbfbc5b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[@id = 'session_nosessionmsg']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='session_nosessionmsg']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>session_nosessionmsg</value>
   </webElementProperties>
</WebElementEntity>
