<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>application_name</name>
   <tag></tag>
   <elementGuidId>7f387ca5-6241-4863-8ffc-e4b3e6a2d13f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@title='Test123File_1']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@tage = 'a' and @title = 'Test123File_1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Test123File_1</value>
   </webElementProperties>
</WebElementEntity>
