<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Cores_arrow</name>
   <tag></tag>
   <elementGuidId>d2c9b194-8c1a-44b6-9335-d78df2a39538</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#accordion__heading-raa-1 > span.unity_down_chevron</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='accordion__heading-raa-1']</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>id(&quot;accordion__heading-raa-1&quot;)/span[@class=&quot;unity_down_chevron&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>unity_down_chevron</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordion__heading-raa-1&quot;)/span[@class=&quot;unity_down_chevron&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion__heading-raa-1']/span</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[2]/div/div/span</value>
   </webElementXpaths>
</WebElementEntity>
