<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>JobStatus</name>
   <tag></tag>
   <elementGuidId>e8153865-f278-4b15-a362-24e8c25cc9de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h6</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(contains(text(), 'Job status: Can Never Run: Insufficient amount of resource: ncpus ') or contains(., 'Job status: Can Never Run: Insufficient amount of resource: ncpus '))]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body[@id='body']/div[3]/div[2]/div/div/div[2]/div/h6</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h6</value>
      <webElementGuid>61dcf5f6-c919-44c3-9ad0-7b75a1ac8852</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>contains</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Job status: Can Never Run: Insufficient amount of resource: ncpus </value>
      <webElementGuid>48f0b882-6f23-4661-a9c2-ed31acb443c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//body[@id='body']/div[3]/div[2]/div/div/div[2]/div/h6</value>
      <webElementGuid>d390be82-efaa-4c67-a7c9-8606f4094129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='`'])[2]/following::h6[1]</value>
      <webElementGuid>44ce8b22-ddec-43c2-99cc-85c6b68a3585</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Alt'])[2]/following::h6[1]</value>
      <webElementGuid>902a6be6-6685-43a1-ad58-6cfdd858ba36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Can Never Run: Insufficient amount of resource: ncpus (R: 100 A: 60 T: 60)']/parent::*</value>
      <webElementGuid>f3f1d82e-d108-4ffc-8b9a-a865b3a0f247</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h6</value>
      <webElementGuid>0b3233df-afec-4f48-9e2e-8a483c5ab619</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
