<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Tooltip_Inputfile</name>
   <tag></tag>
   <elementGuidId>67c8c4d1-b90b-433a-a69f-1db5e971df0d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//body/div[@id='root']/div[1]/div[3]/div[1]/div[1]/div[3]/div[1]/section[1]/div[2]/form[1]/div[6]/div[3]/span[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
