<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WallTime_arrow</name>
   <tag></tag>
   <elementGuidId>22fb1b12-438e-45bd-8f5f-fe1ed2557a28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>id(&quot;accordion__heading-raa-0&quot;)/span[@class=&quot;unity_down_chevron&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
